# Joint configuration for joint_state_publisher_gui

joint_state_publisher:
  ros__parameters:
    # Joint names and default positions
    zeros:
      Revolute3: 0.0
      Revolute4: 0.0
      Revolute6: 0.0
      Revolute_1: 0.0
      Revolute_2: 0.0
      left_pivot_joint1: 0.0
      left_pivot_joint2: 0.0
      right_pivot_joint1: 0.0
      right_pivot_joint2: 0.0
      servo_joint: 0.0

    # Joints to publish
    source_list:
      - Revolute3
      - Revolute4
      - Revolute6
      - Revolute_1
      - Revolute_2
      - left_pivot_joint1
      - left_pivot_joint2
      - right_pivot_joint1
      - right_pivot_joint2
      - servo_joint