"""
Supplementary Export — Data that URDF cannot carry.

Generates:
  - robot_data.yaml: Assembly hierarchy, per-link physics, rigid groups, materials
  - transforms.md:   KaTeX-formatted 4×4 homogeneous transformation matrices

Assemblies tagged "!dummy_*" are excluded
(placeholder convention).

Author: Adrian Valaker Eikeland
"""

import os
import math
from typing import Dict, List, Tuple

from .data_types import (
    RobotModel, LinkNode, JointNode, ExportConfig, Vec3, RPY,
    EXPORTER_VERSION,
)
from ..utils import Logger, is_dummy_assembly_name, yaml_safe_name


# ──────────────────────────────────────────────
# YAML export
# ──────────────────────────────────────────────

def generate_supplementary_yaml(
    model: RobotModel,
    config: ExportConfig,
    pkg_dir: str,
    log: Logger,
) -> str:
    """
    Generate robot_data.yaml with information URDF cannot carry.
    
    Dummy assemblies ("!dummy_*") are
    excluded — these are placeholders meant to be swapped out.
    """
    path = os.path.join(pkg_dir, "robot_data.yaml")
    lines = []
    
    # ── Metadata ──
    lines.append("# Supplementary robot data (beyond URDF)")
    lines.append(f"# Generated by Fusion URDF/XACRO Exporter")
    lines.append("")
    lines.append("metadata:")
    lines.append(f"  design_name: {model.name}")
    lines.append(f"  package_name: {config.package_name}")
    lines.append(f"  exporter_version: '{EXPORTER_VERSION}'")
    lines.append(f"  total_mass_kg: {sum(l.mass_kg for l in model.links.values()):.4f}")
    lines.append(f"  link_count: {len(model.links)}")
    lines.append(f"  joint_count: {len(model.joints)}")
    lines.append(f"  root_link: {model.root_link}")
    lines.append("")
    
    # ── Assemblies (skip dummy modules) ──
    real_assemblies = {
        name: asm for name, asm in model.assemblies.items()
        if not is_dummy_assembly_name(name)
    }
    
    if real_assemblies:
        lines.append("assemblies:")
        for name, asm in sorted(real_assemblies.items()):
            lines.append(f"  {name}:")
            lines.append(f"    links: [{', '.join(asm.links)}]")
            total_mass = sum(
                model.links[ln].mass_kg
                for ln in asm.links if ln in model.links
            )
            lines.append(f"    total_mass_kg: {total_mass:.4f}")
        lines.append("")
    
    # ── Links (skip those in dummy assemblies) ──
    dummy_assemblies = {
        name for name in model.assemblies if is_dummy_assembly_name(name)
    }
    
    lines.append("links:")
    for name in sorted(model.links.keys()):
        link = model.links[name]
        if link.assembly in dummy_assemblies:
            continue
        lines.append(f"  {name}:")
        lines.append(f"    assembly: {link.assembly}")
        lines.append(f"    mass_kg: {link.mass_kg:.6f}")
        lines.append(f"    volume_m3: {link.volume_m3:.8f}")
        
        bx, by, bz = link.bbox_size
        lines.append(f"    bbox_size_m: [{bx:.6f}, {by:.6f}, {bz:.6f}]")
        
        cx, cy, cz = link.com_link_local
        lines.append(f"    com_local_m: [{cx:.6f}, {cy:.6f}, {cz:.6f}]")
        
        inertia = link.inertia_at_com
        lines.append(f"    inertia_at_com:")
        lines.append(f"      ixx: {inertia.ixx:.6e}")
        lines.append(f"      ixy: {inertia.ixy:.6e}")
        lines.append(f"      ixz: {inertia.ixz:.6e}")
        lines.append(f"      iyy: {inertia.iyy:.6e}")
        lines.append(f"      iyz: {inertia.iyz:.6e}")
        lines.append(f"      izz: {inertia.izz:.6e}")
        
        if link.material_name:
            lines.append(f"    material: '{link.material_name}'")
        if link.color_rgb:
            r, g, b = link.color_rgb
            lines.append(f"    color_rgba: [{r:.3f}, {g:.3f}, {b:.3f}, 1.0]")
        
        lines.append(f"    body_count: {link.body_count}")
        lines.append(f"    is_empty: {str(link.is_empty).lower()}")
        if getattr(link, "is_frame_only", False):
            lines.append("    is_frame_only: true")
        if getattr(link, "collision_override", ""):
            lines.append(f"    collision_override: {link.collision_override}")
        
        if link.collision:
            lines.append(f"    collision_source: {link.collision.source}")
            if link.collision.uses_primitive and link.collision.primitive:
                lines.append(f"    collision_shape: {link.collision.primitive.shape}")
        
        if link.needs_mesh_bake:
            bk = link.mesh_bake_offset
            lines.append(f"    bake_offset_m: [{bk[0]:.6f}, {bk[1]:.6f}, {bk[2]:.6f}]")
            mr = getattr(link, "mesh_origin_rpy", (0.0, 0.0, 0.0))
            lines.append(
                f"    mesh_origin_rpy_rad: "
                f"[{mr[0]:.6f}, {mr[1]:.6f}, {mr[2]:.6f}]"
            )

        frame_rule = getattr(link, "frame_rule", "keep")
        if frame_rule != "keep":
            fr = getattr(link, "frame_rebase_rpy", (0.0, 0.0, 0.0))
            lines.append(f"    frame_rule: {frame_rule}")
            lines.append(
                f"    frame_rebase_rpy_rad: "
                f"[{fr[0]:.6f}, {fr[1]:.6f}, {fr[2]:.6f}]"
            )
        
        if link.rigid_group_name:
            lines.append(f"    rigid_group: {yaml_safe_name(link.rigid_group_name)}")

        if getattr(link, "is_merged", False) and link.merged_member_paths:
            # List the original Fusion components folded into this URDF
            # link so a downstream consumer can trace mass/inertia back
            # to its constituents.  Names only — paths would be noisy.
            members = []
            for occ_path in link.merged_member_paths:
                # path_segments[-1] is the component name; we stored that
                # via clean_name in the snapshot, but here we only have
                # the path.  Strip down to the leaf segment.
                leaf = occ_path.rsplit('+', 1)[-1].split(' ', 1)[0]
                # ``!frame_*`` / ``!collision_*`` source names land here
                # unstripped; ``!`` is a YAML tag marker so we drop it.
                members.append(yaml_safe_name(leaf or occ_path))
            lines.append(f"    is_merged: true")
            lines.append(f"    merged_from: [{', '.join(members)}]")
    
    lines.append("")
    
    # ── Joints (skip those involving dummy_ assembly links) ──
    dummy_links = {
        name for name, link in model.links.items()
        if link.assembly in dummy_assemblies
    }
    
    lines.append("joints:")
    for name in sorted(model.joints.keys()):
        joint = model.joints[name]
        if joint.parent_link in dummy_links or joint.child_link in dummy_links:
            continue
        lines.append(f"  {name}:")
        lines.append(f"    type: {joint.joint_type}")
        lines.append(f"    parent: {joint.parent_link}")
        lines.append(f"    child: {joint.child_link}")

        x, y, z = joint.origin_xyz
        lines.append(f"    origin_xyz_m: [{x:.6f}, {y:.6f}, {z:.6f}]")

        r, p, yw = joint.origin_rpy
        lines.append(f"    origin_rpy_rad: [{r:.6f}, {p:.6f}, {yw:.6f}]")

        ax, ay, az = joint.axis
        lines.append(f"    axis: [{ax:.4f}, {ay:.4f}, {az:.4f}]")

        lines.append(f"    is_mount: {str(joint.is_mount).lower()}")
        # ``passive`` tells downstream consumers (e.g. URDF→USD
        # importers) not to attach a position/velocity/effort drive on
        # this joint.  Plugin sets it for joints tagged ``!passive_*``
        # in Fusion (idler wheels, free pivots, four-bar followers).
        lines.append(f"    passive: {str(getattr(joint, 'is_passive', False)).lower()}")

        if joint.limits:
            lines.append(f"    limits:")
            lines.append(f"      lower: {joint.limits.lower:.6f}")
            lines.append(f"      upper: {joint.limits.upper:.6f}")
            lines.append(f"      effort: {joint.limits.effort:.1f}")
            lines.append(f"      velocity: {joint.limits.velocity:.2f}")

    # ── Closing joints (sidecar — closed kinematic chains) ──
    # Joints excluded from the URDF tree because URDF can't model
    # cycles.  Downstream URDF→USD pipelines re-apply these as
    # independent ``UsdPhysics*Joint`` prims (no DriveAPI — passive
    # constraints).  Implicitly all closing joints are passive.
    closing_joints = getattr(model, "closing_joints", None) or {}
    visible_closing = {
        n: j for n, j in closing_joints.items()
        if j.parent_link not in dummy_links and j.child_link not in dummy_links
    }
    lines.append("")
    if visible_closing:
        lines.append("closing_joints:")
        for name in sorted(visible_closing.keys()):
            joint = visible_closing[name]
            lines.append(f"  - name: {name}")
            lines.append(f"    source: {joint.closing_source or 'user_tag'}")
            lines.append(f"    type: {joint.joint_type}")
            lines.append(f"    parent: {joint.parent_link}")
            lines.append(f"    child: {joint.child_link}")

            x, y, z = joint.origin_xyz
            lines.append(f"    origin_xyz_m: [{x:.6f}, {y:.6f}, {z:.6f}]")

            r, p, yw = joint.origin_rpy
            lines.append(f"    origin_rpy_rad: [{r:.6f}, {p:.6f}, {yw:.6f}]")

            ax, ay, az = joint.axis
            lines.append(f"    axis: [{ax:.4f}, {ay:.4f}, {az:.4f}]")

            if joint.limits:
                lines.append(f"    limits:")
                lines.append(f"      lower: {joint.limits.lower:.6f}")
                lines.append(f"      upper: {joint.limits.upper:.6f}")
                lines.append(f"      effort: {joint.limits.effort:.1f}")
                lines.append(f"      velocity: {joint.limits.velocity:.2f}")
    else:
        # Emit an empty section so consumers can rely on the key
        # existing.  ``[]`` is YAML for an empty sequence.
        lines.append("closing_joints: []")

    lines.append("")

    # ── Rigid groups ──
    rg_data = getattr(model, '_rigid_group_collision', {})
    if rg_data:
        lines.append("rigid_groups:")
        # Group by rg_name
        groups: Dict[str, List[str]] = {}
        collision_from: Dict[str, str] = {}
        for member_name, (_, _, rg_name, coll_member) in rg_data.items():
            groups.setdefault(rg_name, []).append(member_name)
            collision_from[rg_name] = coll_member
        for rg_name, members in sorted(groups.items()):
            lines.append(f"  {rg_name}:")
            lines.append(f"    members: [{', '.join(sorted(members))}]")
            lines.append(f"    collision_from: {collision_from[rg_name]}")
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    
    log(f"  → {os.path.relpath(path, pkg_dir)}")
    return path


# ──────────────────────────────────────────────
# KaTeX transform matrices
# ──────────────────────────────────────────────

def _rpy_to_rotation_matrix(
    roll: float, pitch: float, yaw: float
) -> List[List[float]]:
    """Convert RPY (XYZ extrinsic) to 3×3 rotation matrix."""
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    
    return [
        [cy*cp,  cy*sp*sr - sy*cr,  cy*sp*cr + sy*sr],
        [sy*cp,  sy*sp*sr + cy*cr,  sy*sp*cr - cy*sr],
        [-sp,    cp*sr,             cp*cr],
    ]


def _fmt(v: float) -> str:
    """Format a float for KaTeX (clean trailing zeros)."""
    if abs(v) < 1e-10:
        return "0"
    if abs(v - round(v)) < 1e-10:
        return str(int(round(v)))
    s = f"{v:.6f}".rstrip('0').rstrip('.')
    if s == "-0":
        return "0"
    return s


def generate_transforms_doc(
    model: RobotModel,
    pkg_dir: str,
    log: Logger,
) -> str:
    """
    Generate transforms.md with KaTeX 4x4 homogeneous matrices.
    
    Revolute/continuous joints use symbolic q_i with c_i = cos(q_i), s_i = sin(q_i).
    Prismatic joints use symbolic q_i for translation along axis.
    Fixed joints produce numeric matrices.
    Global transforms are expressed as matrix products.
    """
    path = os.path.join(pkg_dir, "docs", "transforms.md")
    os.makedirs(os.path.dirname(path), exist_ok=True)
    
    lines = []
    lines.append(f"# Transformation Matrices - {model.name}")
    lines.append("")
    lines.append("Homogeneous transformation matrices between consecutive frames.")
    lines.append("Convention: URDF RPY (XYZ extrinsic / ZYX intrinsic).")
    lines.append("")
    
    # Build kinematic chain order and assign indices
    joint_list = _kinematic_order(model)
    
    # Assign q indices only to movable joints
    q_index = {}  # joint.name -> index (1-based)
    idx = 1
    for joint in joint_list:
        if joint.joint_type in ("revolute", "prismatic", "continuous"):
            q_index[joint.name] = idx
            idx += 1
    
    # Assign link indices (0-based, root = 0, BFS order)
    link_index = {}  # link_name -> index
    link_order_list = []
    visited = {model.root_link}
    queue = [model.root_link]
    li = 0
    while queue:
        current = queue.pop(0)
        link_index[current] = li
        link_order_list.append(current)
        li += 1
        for joint in joint_list:
            if joint.parent_link == current and joint.child_link not in visited:
                visited.add(joint.child_link)
                queue.append(joint.child_link)
    
    # Notation section
    lines.append("## Notation")
    lines.append("")
    
    # Link table
    lines.append("### Frames")
    lines.append("")
    lines.append("| Index | Link |")
    lines.append("|-------|------|")
    for lname in link_order_list:
        li = link_index[lname]
        lines.append(f"| $L_{{{li}}}$ | {lname} |")
    lines.append("")
    
    # Joint / variable table
    if q_index:
        lines.append("### Joint Variables")
        lines.append("")
        lines.append("| Variable | Joint | Type | From | To |")
        lines.append("|----------|-------|------|------|----|")
        for joint in joint_list:
            if joint.name in q_index:
                i = q_index[joint.name]
                unit = "m" if joint.joint_type == "prismatic" else "rad"
                pi = link_index[joint.parent_link]
                ci_idx = link_index[joint.child_link]
                lines.append(f"| $q_{{{i}}}$ | {joint.name} | "
                              f"{joint.joint_type} ({unit}) | "
                              f"$L_{{{pi}}}$ | $L_{{{ci_idx}}}$ |")
        lines.append("")
        lines.append("Shorthand: $c_i = \\cos(q_i)$, $s_i = \\sin(q_i)$")
        lines.append("")
    
    # Kinematic tree diagram
    lines.append("### Kinematic Tree")
    lines.append("")
    lines.append("```")
    _build_notation_tree(lines, model, joint_list, link_index, q_index)
    lines.append("```")
    lines.append("")
    
    # Table of contents
    lines.append("## Transforms")
    lines.append("")
    
    # Generate per-joint transforms
    for joint in joint_list:
        i = q_index.get(joint.name)
        pi = link_index[joint.parent_link]
        ci_idx = link_index[joint.child_link]
        lines.append(f"## {joint.name}")
        lines.append("")
        lines.append(f"$L_{{{pi}}}$ **{joint.parent_link}** -> "
                      f"$L_{{{ci_idx}}}$ **{joint.child_link}** "
                      f"({joint.joint_type})")
        if i:
            lines.append(f"  Variable: $q_{{{i}}}$")
        lines.append("")
        
        # Parameters
        x, y, z = joint.origin_xyz
        r, p, yw = joint.origin_rpy
        lines.append(f"- **origin xyz**: ({_fmt(x)}, {_fmt(y)}, {_fmt(z)}) m")
        lines.append(f"- **origin rpy**: ({_fmt(r)}, {_fmt(p)}, {_fmt(yw)}) rad")
        if joint.joint_type in ("revolute", "prismatic", "continuous"):
            ax = joint.axis
            lines.append(f"- **axis**: ({_fmt(ax[0])}, {_fmt(ax[1])}, {_fmt(ax[2])})")
            if joint.limits:
                if joint.joint_type == "prismatic":
                    lines.append(f"- **limits**: [{_fmt(joint.limits.lower)}, "
                                  f"{_fmt(joint.limits.upper)}] m")
                else:
                    lines.append(f"- **limits**: [{_fmt(joint.limits.lower)}, "
                                  f"{_fmt(joint.limits.upper)}] rad "
                                  f"([{_fmt(math.degrees(joint.limits.lower))}deg, "
                                  f"{_fmt(math.degrees(joint.limits.upper))}deg])")
        lines.append("")
        
        # Local transform matrix
        lines.append("### Local Transform")
        lines.append("")
        
        if joint.joint_type == "fixed":
            # Numeric matrix
            R = _rpy_to_rotation_matrix(r, p, yw)
            lines.append("$$")
            lines.append(f"T^{{{pi}}}_{{{ci_idx}}} = "
                          f"\\begin{{bmatrix}}")
            for row_idx in range(3):
                entries = [_fmt(R[row_idx][j]) for j in range(3)]
                entries.append(_fmt([x, y, z][row_idx]))
                lines.append(" & ".join(entries) + " \\\\")
            lines.append("0 & 0 & 0 & 1 \\\\")
            lines.append("\\end{bmatrix}")
            lines.append("$$")
        
        elif joint.joint_type in ("revolute", "continuous"):
            # Symbolic matrix with rotation about axis
            ax = joint.axis
            _write_symbolic_revolute(lines, joint, i, x, y, z, r, p, yw, ax, pi, ci_idx)
        
        elif joint.joint_type == "prismatic":
            # Symbolic matrix with translation along axis
            ax = joint.axis
            _write_symbolic_prismatic(lines, joint, i, x, y, z, r, p, yw, ax, pi, ci_idx)
        
        lines.append("")
        lines.append("---")
        lines.append("")
    
    # Global transform chain
    lines.append("## Global Transform Chains")
    lines.append("")
    lines.append("Transform from root $L_0$ to any link, as product of "
                  "local transforms along the kinematic chain.")
    lines.append("")
    
    # Build parent map
    parent_chain: Dict[str, List[str]] = {}
    for joint in joint_list:
        chain = parent_chain.get(joint.parent_link, []).copy()
        chain.append(joint.name)
        parent_chain[joint.child_link] = chain
    
    for joint in joint_list:
        chain = parent_chain.get(joint.child_link, [])
        if len(chain) <= 1:
            continue
        
        ci_idx = link_index[joint.child_link]
        factors = []
        for jn in chain:
            jj = model.joints[jn]
            pi = link_index[jj.parent_link]
            cj = link_index[jj.child_link]
            qi = q_index.get(jn)
            if qi:
                factors.append(f"T^{{{pi}}}_{{{cj}}}(q_{{{qi}}})")
            else:
                factors.append(f"T^{{{pi}}}_{{{cj}}}")
        
        child_name = joint.child_link
        chain_str = ' \\cdot '.join(factors)
        lines.append(f"$$T^{{0}}_{{{ci_idx}}} = "
                      f"{chain_str}"
                      f"\\quad (L_0 \\to L_{{{ci_idx}}}: \\text{{{child_name}}})$$")
        lines.append("")
    
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    
    log(f"  -> docs/transforms.md")
    return path


def _write_symbolic_revolute(
    lines: list, joint, i: int,
    tx: float, ty: float, tz: float,
    roll: float, pitch: float, yaw: float,
    axis: tuple,
    pi: int = 0, ci_idx: int = 0,
):
    """Write symbolic 4x4 for revolute joint with Rot(axis, q_i)."""
    ci = f"c_{{{i}}}"
    si = f"s_{{{i}}}"
    t_label = f"T^{{{pi}}}_{{{ci_idx}}}(q_{{{i}}})"
    
    # Pre-rotation from fixed RPY offset
    R_fixed = _rpy_to_rotation_matrix(roll, pitch, yaw)
    has_fixed_rot = any(
        abs(R_fixed[r][c] - (1 if r == c else 0)) > 1e-10
        for r in range(3) for c in range(3)
    )
    
    # Determine rotation axis
    ax, ay, az = axis
    
    if has_fixed_rot:
        # Complex case: T = T_fixed * Rot(axis, q_i)
        lines.append(f"${t_label} = T_{{fixed}} \\cdot R_{{axis}}(q_{{{i}}})$ where:")
        lines.append("")
        # Show fixed part
        lines.append("$$")
        lines.append(f"T_{{fixed}} = \\begin{{bmatrix}}")
        for row_idx in range(3):
            entries = [_fmt(R_fixed[row_idx][j]) for j in range(3)]
            entries.append(_fmt([tx, ty, tz][row_idx]))
            lines.append(" & ".join(entries) + " \\\\")
        lines.append("0 & 0 & 0 & 1 \\\\")
        lines.append("\\end{bmatrix}")
        lines.append("$$")
        lines.append("")
    
    # Show rotation matrix about axis
    label = t_label if not has_fixed_rot else f"R_{{axis}}(q_{{{i}}})"
    lines.append("$$")
    if abs(az) > 0.9:
        # Rotation about Z
        sign = "" if az > 0 else "-"
        nsign = "-" if az > 0 else ""
        lines.append(f"{label} = \\begin{{bmatrix}}")
        lines.append(f"{ci} & {nsign}{si} & 0 & {_fmt(tx) if not has_fixed_rot else '0'} \\\\")
        lines.append(f"{sign}{si} & {ci} & 0 & {_fmt(ty) if not has_fixed_rot else '0'} \\\\")
        lines.append(f"0 & 0 & 1 & {_fmt(tz) if not has_fixed_rot else '0'} \\\\")
        lines.append("0 & 0 & 0 & 1 \\\\")
    elif abs(ay) > 0.9:
        # Rotation about Y
        sign = "" if ay > 0 else "-"
        nsign = "-" if ay > 0 else ""
        lines.append(f"{label} = \\begin{{bmatrix}}")
        lines.append(f"{ci} & 0 & {sign}{si} & {_fmt(tx) if not has_fixed_rot else '0'} \\\\")
        lines.append(f"0 & 1 & 0 & {_fmt(ty) if not has_fixed_rot else '0'} \\\\")
        lines.append(f"{nsign}{si} & 0 & {ci} & {_fmt(tz) if not has_fixed_rot else '0'} \\\\")
        lines.append("0 & 0 & 0 & 1 \\\\")
    elif abs(ax) > 0.9:
        # Rotation about X
        sign = "" if ax > 0 else "-"
        nsign = "-" if ax > 0 else ""
        lines.append(f"{label} = \\begin{{bmatrix}}")
        lines.append(f"1 & 0 & 0 & {_fmt(tx) if not has_fixed_rot else '0'} \\\\")
        lines.append(f"0 & {ci} & {nsign}{si} & {_fmt(ty) if not has_fixed_rot else '0'} \\\\")
        lines.append(f"0 & {sign}{si} & {ci} & {_fmt(tz) if not has_fixed_rot else '0'} \\\\")
        lines.append("0 & 0 & 0 & 1 \\\\")
    else:
        # General axis - Rodrigues
        lines.append(f"{label} = "
                      f"\\text{{Rodrigues}}(\\hat{{k}}, q_{{{i}}})")
        lines.append("\\\\")
    
    lines.append("\\end{bmatrix}")
    lines.append("$$")


def _write_symbolic_prismatic(
    lines: list, joint, i: int,
    tx: float, ty: float, tz: float,
    roll: float, pitch: float, yaw: float,
    axis: tuple,
    pi: int = 0, ci_idx: int = 0,
):
    """Write symbolic 4x4 for prismatic joint with Trans(axis, q_i)."""
    R_fixed = _rpy_to_rotation_matrix(roll, pitch, yaw)
    ax, ay, az = axis
    qi = f"q_{{{i}}}"
    
    # Translation components: fixed + q_i * axis
    def _tx_sym(fixed_val, axis_comp):
        f = _fmt(fixed_val)
        if abs(axis_comp) > 0.9:
            sign = "+" if axis_comp > 0 else "-"
            return f"{f} {sign} {qi}" if f != "0" else f"{'' if axis_comp > 0 else '-'}{qi}"
        return f
    
    tx_s = _tx_sym(tx, ax)
    ty_s = _tx_sym(ty, ay)
    tz_s = _tx_sym(tz, az)
    
    lines.append("$$")
    lines.append(f"T^{{{pi}}}_{{{ci_idx}}}(q_{{{i}}}) = "
                  f"\\begin{{bmatrix}}")
    for row_idx in range(3):
        entries = [_fmt(R_fixed[row_idx][j]) for j in range(3)]
        entries.append([tx_s, ty_s, tz_s][row_idx])
        lines.append(" & ".join(entries) + " \\\\")
    lines.append("0 & 0 & 0 & 1 \\\\")
    lines.append("\\end{bmatrix}")
    lines.append("$$")


def _kinematic_order(model: RobotModel) -> List[JointNode]:
    """Return joints in kinematic tree order (BFS from root)."""
    ordered = []
    visited = {model.root_link}
    queue = [model.root_link]
    
    # Build child map
    children: Dict[str, List[JointNode]] = {}
    for j in model.joints.values():
        children.setdefault(j.parent_link, []).append(j)
    
    while queue:
        current = queue.pop(0)
        for joint in children.get(current, []):
            if joint.child_link not in visited:
                ordered.append(joint)
                visited.add(joint.child_link)
                queue.append(joint.child_link)
    
    return ordered


def _build_notation_tree(
    lines: list,
    model: RobotModel,
    joint_list: list,
    link_index: Dict[str, int],
    q_index: Dict[str, int],
    link: str = None,
    prefix: str = "",
    is_last: bool = True,
):
    """Build ASCII kinematic tree with L_i indices and q_i labels."""
    if link is None:
        link = model.root_link
    
    li = link_index.get(link, "?")
    lines.append(f"{prefix}L{li}: {link}")
    
    # Find children
    children = []
    for joint in joint_list:
        if joint.parent_link == link:
            children.append(joint)
    
    for idx, joint in enumerate(children):
        is_last_child = (idx == len(children) - 1)
        connector = "  +-- " if is_last_child else "  |-- "
        qi = q_index.get(joint.name)
        q_label = f" (q{qi})" if qi else ""
        
        lines.append(f"{prefix}{connector}[{joint.joint_type}] {joint.name}{q_label}")
        
        child_prefix = prefix + ("      " if is_last_child else "  |   ")
        _build_notation_tree(
            lines, model, joint_list, link_index, q_index,
            joint.child_link, child_prefix, is_last_child,
        )


def _mat_mul_4x4(A: List[List[float]], B: List[List[float]]) -> List[List[float]]:
    """Multiply two 4×4 matrices."""
    result = [[0.0]*4 for _ in range(4)]
    for i in range(4):
        for j in range(4):
            for k in range(4):
                result[i][j] += A[i][k] * B[k][j]
    return result
